name: Azure Static Web Apps CI/CD

variables:
  - template: 'templates/variables.yaml'

trigger:
  - develop

jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    pool:
      vmImage: $(VM_IMAGE)
    variables:
      - group: Azure-Static-Web-Apps-calm-plant-0ecbec603-variable-group
    steps:
      - template: 'templates/git-checkout-code.yaml'
      - template: 'templates/unit-tests.yaml'
      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_PLANT_0ECBEC603)
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          app_build_command: 'npm run build-dev-ebp'
          output_location: 'dist' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
